### PR TITLE
Adding in a Reverse Function

### PR DESCRIPTION
**Pull request by mkapl**
To complement the current set of functions I've added in a reverse sequence function

### CODE REVIEW

**Review by tnrich — APPROVED** [review]
Excellent thanks @mkapl 

Just out of curiosity, do you have a use case for this function?

-Thomas

**Comment by mkapl** [comment]
BTW -is there any way I can PR to the vs util?

On May 18, 2022, at 17:49, Thomas Rich ***@***.***> wrote:

﻿

@tnrich approved this pull request.

Excellent thanks @mkapl<https://github.com/mkapl>

Just out of curiosity, do you have a use case for this function?

-Thomas

**Comment by tnrich** [comment]
@mkapl ok this is landing in ve-sequence-utils@5.1.16

**Comment by mkapl** [comment]
Sorry to bother you – I see that the command is now in VS code but it does not seem to be functioning and can't figure out a fix myself

**Comment by tnrich** [comment]
@mkapl whoops must've messed something up. I'll look into a fix for this

**Comment by tnrich** [comment]
@mkapl looks like the updated code I used for the reverse function got compiled "incorrectly"

this code, which works correctly: 
```js
return [...s].reverse().join("");
```
got compiled into 
```js
return [].concat(s).reverse().join("");
```
which does not work correctly. 

I'm reverting to use the slightly more verbose but simpler method you used to reverse the text originally.

Should land in v0.0.12 which I just published so should be available in a few minutes

**Comment by mkapl** [comment]
Yeah - I often hand align individual sequences if a sequencing run looks bad and it’s really handy to be able to quickly reverse the string in addition to RC-ing and complementing.

It’s also helpful for when I build some workflows that have some ssDNA as those are sometimes useful to work with the reverse to see how it aligns with a certain sequence.


Best, Matias
On May 18, 2022, at 17:49, Thomas Rich ***@***.***> wrote:

﻿

@tnrich approved this pull request.

Excellent thanks @mkapl<https://github.com/mkapl>

Just out of curiosity, do you have a use case for this function?

-Thomas

**Pull request merged**
